#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEVRI.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="APSWSEVRI")]
	public partial class SEVRIDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAdministracion(Administracion instance);
    partial void UpdateAdministracion(Administracion instance);
    partial void DeleteAdministracion(Administracion instance);
    partial void InsertDependencia(Dependencia instance);
    partial void UpdateDependencia(Dependencia instance);
    partial void DeleteDependencia(Dependencia instance);
    partial void InsertDiccionario(Diccionario instance);
    partial void UpdateDiccionario(Diccionario instance);
    partial void DeleteDiccionario(Diccionario instance);
    partial void InsertDireccionDirect(DireccionDirect instance);
    partial void UpdateDireccionDirect(DireccionDirect instance);
    partial void DeleteDireccionDirect(DireccionDirect instance);
    partial void InsertEspecifico(Especifico instance);
    partial void UpdateEspecifico(Especifico instance);
    partial void DeleteEspecifico(Especifico instance);
    partial void InsertEvalucionRiesgo(EvalucionRiesgo instance);
    partial void UpdateEvalucionRiesgo(EvalucionRiesgo instance);
    partial void DeleteEvalucionRiesgo(EvalucionRiesgo instance);
    partial void InsertGenerales(Generales instance);
    partial void UpdateGenerales(Generales instance);
    partial void DeleteGenerales(Generales instance);
    partial void InsertMedidadControlRiesgoPropuesto(MedidadControlRiesgoPropuesto instance);
    partial void UpdateMedidadControlRiesgoPropuesto(MedidadControlRiesgoPropuesto instance);
    partial void DeleteMedidadControlRiesgoPropuesto(MedidadControlRiesgoPropuesto instance);
    partial void InsertRiesgos(Riesgos instance);
    partial void UpdateRiesgos(Riesgos instance);
    partial void DeleteRiesgos(Riesgos instance);
    #endregion
		
		public SEVRIDataContext() : 
				base(global::SEVRI.Properties.Settings.Default.APSWSEVRIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SEVRIDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SEVRIDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SEVRIDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SEVRIDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Administracion> Administracion
		{
			get
			{
				return this.GetTable<Administracion>();
			}
		}
		
		public System.Data.Linq.Table<Dependencia> Dependencia
		{
			get
			{
				return this.GetTable<Dependencia>();
			}
		}
		
		public System.Data.Linq.Table<Diccionario> Diccionario
		{
			get
			{
				return this.GetTable<Diccionario>();
			}
		}
		
		public System.Data.Linq.Table<DireccionDirect> DireccionDirect
		{
			get
			{
				return this.GetTable<DireccionDirect>();
			}
		}
		
		public System.Data.Linq.Table<Especifico> Especifico
		{
			get
			{
				return this.GetTable<Especifico>();
			}
		}
		
		public System.Data.Linq.Table<EvaluacionControlesActualesRiesgo> EvaluacionControlesActualesRiesgo
		{
			get
			{
				return this.GetTable<EvaluacionControlesActualesRiesgo>();
			}
		}
		
		public System.Data.Linq.Table<EvalucionRiesgo> EvalucionRiesgo
		{
			get
			{
				return this.GetTable<EvalucionRiesgo>();
			}
		}
		
		public System.Data.Linq.Table<Generales> Generales
		{
			get
			{
				return this.GetTable<Generales>();
			}
		}
		
		public System.Data.Linq.Table<MedidadControlRiesgoPropuesto> MedidadControlRiesgoPropuesto
		{
			get
			{
				return this.GetTable<MedidadControlRiesgoPropuesto>();
			}
		}
		
		public System.Data.Linq.Table<RiesgoPropuesto> RiesgoPropuesto
		{
			get
			{
				return this.GetTable<RiesgoPropuesto>();
			}
		}
		
		public System.Data.Linq.Table<Riesgos> Riesgos
		{
			get
			{
				return this.GetTable<Riesgos>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.inser")]
		public int inser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(100)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contra", DbType="VarChar(50)")] string contra)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contra);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PrAdmi")]
		public void PrAdmi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoRiesgo", DbType="VarChar(50)")] string tipoRiesgo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Prioridad", DbType="VarChar(50)")] string prioridad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NivelRiesgoInherente", DbType="VarChar(50)")] string nivelRiesgoInherente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NivelRiesgoResidual", DbType="VarChar(50)")] string nivelRiesgoResidual, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GradoAfectacion", DbType="VarChar(50)")] string gradoAfectacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Importancia", DbType="VarChar(150)")] string importancia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Variacion", DbType="VarChar(150)")] string variacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Costo", DbType="Int")] System.Nullable<int> costo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Aceptabilidad", DbType="VarChar(250)")] string aceptabilidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resultado", DbType="VarChar(50)")] string resultado)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tipoRiesgo, prioridad, nivelRiesgoInherente, nivelRiesgoResidual, gradoAfectacion, importancia, variacion, costo, aceptabilidad, resultado);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PrEvalu")]
		public void PrEvalu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(50)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ControlActual", DbType="VarChar(50)")] string controlActual, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(250)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Probabilidad", DbType="VarChar(50)")] string probabilidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Impacto", DbType="VarChar(50)")] string impacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NivelRiesgoInherente", DbType="VarChar(50)")] string nivelRiesgoInherente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NivelRiesgoResidual", DbType="VarChar(50)")] string nivelRiesgoResidual, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaApli", DbType="Date")] System.Nullable<System.DateTime> fechaApli)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, controlActual, descripcion, probabilidad, impacto, nivelRiesgoInherente, nivelRiesgoResidual, fechaApli);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProDiccionario")]
		public void ProDiccionario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(50)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Categoria", DbType="VarChar(50)")] string categoria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Subcategoria", DbType="VarChar(50)")] string subcategoria)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, nombre, descripcion, categoria, subcategoria);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProEspecif")]
		public void ProEspecif([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoEspe", DbType="VarChar(50)")] string codigoEspe, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AreaRiesgo", DbType="VarChar(50)")] string areaRiesgo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DependenciaRiesgo", DbType="VarChar(50)")] string dependenciaRiesgo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Causa", DbType="VarChar(50)")] string causa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Evento", DbType="VarChar(50)")] string evento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaIdenti", DbType="Date")] System.Nullable<System.DateTime> fechaIdenti, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Consecuencia", DbType="VarChar(50)")] string consecuencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(50)")] string codigo)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoEspe, areaRiesgo, dependenciaRiesgo, causa, evento, fechaIdenti, consecuencia, codigo);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProGenerales")]
		public void ProGenerales([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoGeneral", DbType="VarChar(50)")] string codigoGeneral, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Causa", DbType="VarChar(50)")] string causa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Consecuencia", DbType="VarChar(50)")] string consecuencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Evento", DbType="VarChar(50)")] string evento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaIdenti", DbType="Date")] System.Nullable<System.DateTime> fechaIdenti, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="VarChar(50)")] string codigo)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoGeneral, nombre, causa, consecuencia, evento, fechaIdenti, codigo);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administracion")]
	public partial class Administracion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TipoRiesgo;
		
		private int _CodigoAdministra;
		
		private string _ToleranciaRiesgo;
		
		private System.Nullable<int> _NivelRiesgoInherente;
		
		private System.Nullable<int> _NivelRiesgo;
		
		private string _GradoAfectacion;
		
		private string _ImportanciadelObjdelProceso;
		
		private string _VariacionNivelRiesgoControles;
		
		private System.Nullable<int> _AnalisisCosto;
		
		private string _AceptabilidadRiesgo;
		
		private System.Nullable<int> _Codigo;
		
		private EntityRef<Riesgos> _Riesgos;
		
		private EntityRef<Riesgos> _Riesgos1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTipoRiesgoChanging(string value);
    partial void OnTipoRiesgoChanged();
    partial void OnCodigoAdministraChanging(int value);
    partial void OnCodigoAdministraChanged();
    partial void OnToleranciaRiesgoChanging(string value);
    partial void OnToleranciaRiesgoChanged();
    partial void OnNivelRiesgoInherenteChanging(System.Nullable<int> value);
    partial void OnNivelRiesgoInherenteChanged();
    partial void OnNivelRiesgoChanging(System.Nullable<int> value);
    partial void OnNivelRiesgoChanged();
    partial void OnGradoAfectacionChanging(string value);
    partial void OnGradoAfectacionChanged();
    partial void OnImportanciadelObjdelProcesoChanging(string value);
    partial void OnImportanciadelObjdelProcesoChanged();
    partial void OnVariacionNivelRiesgoControlesChanging(string value);
    partial void OnVariacionNivelRiesgoControlesChanged();
    partial void OnAnalisisCostoChanging(System.Nullable<int> value);
    partial void OnAnalisisCostoChanged();
    partial void OnAceptabilidadRiesgoChanging(string value);
    partial void OnAceptabilidadRiesgoChanged();
    partial void OnCodigoChanging(System.Nullable<int> value);
    partial void OnCodigoChanged();
    #endregion
		
		public Administracion()
		{
			this._Riesgos = default(EntityRef<Riesgos>);
			this._Riesgos1 = default(EntityRef<Riesgos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoRiesgo", DbType="VarChar(100)")]
		public string TipoRiesgo
		{
			get
			{
				return this._TipoRiesgo;
			}
			set
			{
				if ((this._TipoRiesgo != value))
				{
					this.OnTipoRiesgoChanging(value);
					this.SendPropertyChanging();
					this._TipoRiesgo = value;
					this.SendPropertyChanged("TipoRiesgo");
					this.OnTipoRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoAdministra", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CodigoAdministra
		{
			get
			{
				return this._CodigoAdministra;
			}
			set
			{
				if ((this._CodigoAdministra != value))
				{
					this.OnCodigoAdministraChanging(value);
					this.SendPropertyChanging();
					this._CodigoAdministra = value;
					this.SendPropertyChanged("CodigoAdministra");
					this.OnCodigoAdministraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToleranciaRiesgo", DbType="VarChar(100)")]
		public string ToleranciaRiesgo
		{
			get
			{
				return this._ToleranciaRiesgo;
			}
			set
			{
				if ((this._ToleranciaRiesgo != value))
				{
					this.OnToleranciaRiesgoChanging(value);
					this.SendPropertyChanging();
					this._ToleranciaRiesgo = value;
					this.SendPropertyChanged("ToleranciaRiesgo");
					this.OnToleranciaRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelRiesgoInherente", DbType="Int")]
		public System.Nullable<int> NivelRiesgoInherente
		{
			get
			{
				return this._NivelRiesgoInherente;
			}
			set
			{
				if ((this._NivelRiesgoInherente != value))
				{
					this.OnNivelRiesgoInherenteChanging(value);
					this.SendPropertyChanging();
					this._NivelRiesgoInherente = value;
					this.SendPropertyChanged("NivelRiesgoInherente");
					this.OnNivelRiesgoInherenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelRiesgo", DbType="Int")]
		public System.Nullable<int> NivelRiesgo
		{
			get
			{
				return this._NivelRiesgo;
			}
			set
			{
				if ((this._NivelRiesgo != value))
				{
					this.OnNivelRiesgoChanging(value);
					this.SendPropertyChanging();
					this._NivelRiesgo = value;
					this.SendPropertyChanged("NivelRiesgo");
					this.OnNivelRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradoAfectacion", DbType="VarChar(100)")]
		public string GradoAfectacion
		{
			get
			{
				return this._GradoAfectacion;
			}
			set
			{
				if ((this._GradoAfectacion != value))
				{
					this.OnGradoAfectacionChanging(value);
					this.SendPropertyChanging();
					this._GradoAfectacion = value;
					this.SendPropertyChanged("GradoAfectacion");
					this.OnGradoAfectacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportanciadelObjdelProceso", DbType="VarChar(100)")]
		public string ImportanciadelObjdelProceso
		{
			get
			{
				return this._ImportanciadelObjdelProceso;
			}
			set
			{
				if ((this._ImportanciadelObjdelProceso != value))
				{
					this.OnImportanciadelObjdelProcesoChanging(value);
					this.SendPropertyChanging();
					this._ImportanciadelObjdelProceso = value;
					this.SendPropertyChanged("ImportanciadelObjdelProceso");
					this.OnImportanciadelObjdelProcesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VariacionNivelRiesgoControles", DbType="VarChar(100)")]
		public string VariacionNivelRiesgoControles
		{
			get
			{
				return this._VariacionNivelRiesgoControles;
			}
			set
			{
				if ((this._VariacionNivelRiesgoControles != value))
				{
					this.OnVariacionNivelRiesgoControlesChanging(value);
					this.SendPropertyChanging();
					this._VariacionNivelRiesgoControles = value;
					this.SendPropertyChanged("VariacionNivelRiesgoControles");
					this.OnVariacionNivelRiesgoControlesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnalisisCosto", DbType="Int")]
		public System.Nullable<int> AnalisisCosto
		{
			get
			{
				return this._AnalisisCosto;
			}
			set
			{
				if ((this._AnalisisCosto != value))
				{
					this.OnAnalisisCostoChanging(value);
					this.SendPropertyChanging();
					this._AnalisisCosto = value;
					this.SendPropertyChanged("AnalisisCosto");
					this.OnAnalisisCostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AceptabilidadRiesgo", DbType="VarChar(100)")]
		public string AceptabilidadRiesgo
		{
			get
			{
				return this._AceptabilidadRiesgo;
			}
			set
			{
				if ((this._AceptabilidadRiesgo != value))
				{
					this.OnAceptabilidadRiesgoChanging(value);
					this.SendPropertyChanging();
					this._AceptabilidadRiesgo = value;
					this.SendPropertyChanged("AceptabilidadRiesgo");
					this.OnAceptabilidadRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int")]
		public System.Nullable<int> Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					if ((this._Riesgos.HasLoadedOrAssignedValue || this._Riesgos1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Riesgos_Administracion", Storage="_Riesgos", ThisKey="Codigo", OtherKey="Codigo", IsForeignKey=true)]
		public Riesgos Riesgos
		{
			get
			{
				return this._Riesgos.Entity;
			}
			set
			{
				Riesgos previousValue = this._Riesgos.Entity;
				if (((previousValue != value) 
							|| (this._Riesgos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Riesgos.Entity = null;
						previousValue.Administracion.Remove(this);
					}
					this._Riesgos.Entity = value;
					if ((value != null))
					{
						value.Administracion.Add(this);
						this._Codigo = value.Codigo;
					}
					else
					{
						this._Codigo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Riesgos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Riesgos_Administracion1", Storage="_Riesgos1", ThisKey="Codigo", OtherKey="Codigo", IsForeignKey=true)]
		public Riesgos Riesgos1
		{
			get
			{
				return this._Riesgos1.Entity;
			}
			set
			{
				Riesgos previousValue = this._Riesgos1.Entity;
				if (((previousValue != value) 
							|| (this._Riesgos1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Riesgos1.Entity = null;
						previousValue.Administracion1.Remove(this);
					}
					this._Riesgos1.Entity = value;
					if ((value != null))
					{
						value.Administracion1.Add(this);
						this._Codigo = value.Codigo;
					}
					else
					{
						this._Codigo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Riesgos1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dependencia")]
	public partial class Dependencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nombre;
		
		private string _Direccion;
		
		private EntitySet<Especifico> _Especifico;
		
		private EntityRef<DireccionDirect> _DireccionDirect;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    #endregion
		
		public Dependencia()
		{
			this._Especifico = new EntitySet<Especifico>(new Action<Especifico>(this.attach_Especifico), new Action<Especifico>(this.detach_Especifico));
			this._DireccionDirect = default(EntityRef<DireccionDirect>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					if (this._DireccionDirect.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dependencia_Especifico", Storage="_Especifico", ThisKey="Nombre", OtherKey="Dependencia")]
		public EntitySet<Especifico> Especifico
		{
			get
			{
				return this._Especifico;
			}
			set
			{
				this._Especifico.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DireccionDirect_Dependencia", Storage="_DireccionDirect", ThisKey="Direccion", OtherKey="Codigo", IsForeignKey=true)]
		public DireccionDirect DireccionDirect
		{
			get
			{
				return this._DireccionDirect.Entity;
			}
			set
			{
				DireccionDirect previousValue = this._DireccionDirect.Entity;
				if (((previousValue != value) 
							|| (this._DireccionDirect.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DireccionDirect.Entity = null;
						previousValue.Dependencia.Remove(this);
					}
					this._DireccionDirect.Entity = value;
					if ((value != null))
					{
						value.Dependencia.Add(this);
						this._Direccion = value.Codigo;
					}
					else
					{
						this._Direccion = default(string);
					}
					this.SendPropertyChanged("DireccionDirect");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Especifico(Especifico entity)
		{
			this.SendPropertyChanging();
			entity.Dependencia1 = this;
		}
		
		private void detach_Especifico(Especifico entity)
		{
			this.SendPropertyChanging();
			entity.Dependencia1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Diccionario")]
	public partial class Diccionario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Codigo;
		
		private string _Causa;
		
		private string _Descripcion;
		
		private string _TipoRiesgo;
		
		private string _Categoria;
		
		private string _SubCategoria;
		
		private EntitySet<Generales> _Generales;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnCausaChanging(string value);
    partial void OnCausaChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnTipoRiesgoChanging(string value);
    partial void OnTipoRiesgoChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnSubCategoriaChanging(string value);
    partial void OnSubCategoriaChanged();
    #endregion
		
		public Diccionario()
		{
			this._Generales = new EntitySet<Generales>(new Action<Generales>(this.attach_Generales), new Action<Generales>(this.detach_Generales));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Causa", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Causa
		{
			get
			{
				return this._Causa;
			}
			set
			{
				if ((this._Causa != value))
				{
					this.OnCausaChanging(value);
					this.SendPropertyChanging();
					this._Causa = value;
					this.SendPropertyChanged("Causa");
					this.OnCausaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoRiesgo", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string TipoRiesgo
		{
			get
			{
				return this._TipoRiesgo;
			}
			set
			{
				if ((this._TipoRiesgo != value))
				{
					this.OnTipoRiesgoChanging(value);
					this.SendPropertyChanging();
					this._TipoRiesgo = value;
					this.SendPropertyChanged("TipoRiesgo");
					this.OnTipoRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(150)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoria", DbType="VarChar(150)")]
		public string SubCategoria
		{
			get
			{
				return this._SubCategoria;
			}
			set
			{
				if ((this._SubCategoria != value))
				{
					this.OnSubCategoriaChanging(value);
					this.SendPropertyChanging();
					this._SubCategoria = value;
					this.SendPropertyChanged("SubCategoria");
					this.OnSubCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Diccionario_Generales", Storage="_Generales", ThisKey="Codigo", OtherKey="CodigoCausa")]
		public EntitySet<Generales> Generales
		{
			get
			{
				return this._Generales;
			}
			set
			{
				this._Generales.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Generales(Generales entity)
		{
			this.SendPropertyChanging();
			entity.Diccionario = this;
		}
		
		private void detach_Generales(Generales entity)
		{
			this.SendPropertyChanging();
			entity.Diccionario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DireccionDirect")]
	public partial class DireccionDirect : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Codigo;
		
		private string _Nombre;
		
		private EntitySet<Dependencia> _Dependencia;
		
		private EntitySet<Especifico> _Especifico;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public DireccionDirect()
		{
			this._Dependencia = new EntitySet<Dependencia>(new Action<Dependencia>(this.attach_Dependencia), new Action<Dependencia>(this.detach_Dependencia));
			this._Especifico = new EntitySet<Especifico>(new Action<Especifico>(this.attach_Especifico), new Action<Especifico>(this.detach_Especifico));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DireccionDirect_Dependencia", Storage="_Dependencia", ThisKey="Codigo", OtherKey="Direccion")]
		public EntitySet<Dependencia> Dependencia
		{
			get
			{
				return this._Dependencia;
			}
			set
			{
				this._Dependencia.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DireccionDirect_Especifico", Storage="_Especifico", ThisKey="Codigo", OtherKey="Direccion")]
		public EntitySet<Especifico> Especifico
		{
			get
			{
				return this._Especifico;
			}
			set
			{
				this._Especifico.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dependencia(Dependencia entity)
		{
			this.SendPropertyChanging();
			entity.DireccionDirect = this;
		}
		
		private void detach_Dependencia(Dependencia entity)
		{
			this.SendPropertyChanging();
			entity.DireccionDirect = null;
		}
		
		private void attach_Especifico(Especifico entity)
		{
			this.SendPropertyChanging();
			entity.DireccionDirect = this;
		}
		
		private void detach_Especifico(Especifico entity)
		{
			this.SendPropertyChanging();
			entity.DireccionDirect = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Especifico")]
	public partial class Especifico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Objetivo;
		
		private string _CodigoRiesgo;
		
		private string _CausaEspecifico;
		
		private string _Direccion;
		
		private string _Dependencia;
		
		private string _DescripcionCausa;
		
		private string _DescripcionEvento;
		
		private string _DescripcionConsecuencia;
		
		private System.DateTime _FechaIdentificacion;
		
		private EntityRef<Dependencia> _Dependencia1;
		
		private EntityRef<DireccionDirect> _DireccionDirect;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnObjetivoChanging(string value);
    partial void OnObjetivoChanged();
    partial void OnCodigoRiesgoChanging(string value);
    partial void OnCodigoRiesgoChanged();
    partial void OnCausaEspecificoChanging(string value);
    partial void OnCausaEspecificoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnDependenciaChanging(string value);
    partial void OnDependenciaChanged();
    partial void OnDescripcionCausaChanging(string value);
    partial void OnDescripcionCausaChanged();
    partial void OnDescripcionEventoChanging(string value);
    partial void OnDescripcionEventoChanged();
    partial void OnDescripcionConsecuenciaChanging(string value);
    partial void OnDescripcionConsecuenciaChanged();
    partial void OnFechaIdentificacionChanging(System.DateTime value);
    partial void OnFechaIdentificacionChanged();
    #endregion
		
		public Especifico()
		{
			this._Dependencia1 = default(EntityRef<Dependencia>);
			this._DireccionDirect = default(EntityRef<DireccionDirect>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Objetivo", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Objetivo
		{
			get
			{
				return this._Objetivo;
			}
			set
			{
				if ((this._Objetivo != value))
				{
					this.OnObjetivoChanging(value);
					this.SendPropertyChanging();
					this._Objetivo = value;
					this.SendPropertyChanged("Objetivo");
					this.OnObjetivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoRiesgo", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodigoRiesgo
		{
			get
			{
				return this._CodigoRiesgo;
			}
			set
			{
				if ((this._CodigoRiesgo != value))
				{
					this.OnCodigoRiesgoChanging(value);
					this.SendPropertyChanging();
					this._CodigoRiesgo = value;
					this.SendPropertyChanged("CodigoRiesgo");
					this.OnCodigoRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CausaEspecifico", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string CausaEspecifico
		{
			get
			{
				return this._CausaEspecifico;
			}
			set
			{
				if ((this._CausaEspecifico != value))
				{
					this.OnCausaEspecificoChanging(value);
					this.SendPropertyChanging();
					this._CausaEspecifico = value;
					this.SendPropertyChanged("CausaEspecifico");
					this.OnCausaEspecificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					if (this._DireccionDirect.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dependencia", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Dependencia
		{
			get
			{
				return this._Dependencia;
			}
			set
			{
				if ((this._Dependencia != value))
				{
					if (this._Dependencia1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDependenciaChanging(value);
					this.SendPropertyChanging();
					this._Dependencia = value;
					this.SendPropertyChanged("Dependencia");
					this.OnDependenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionCausa", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string DescripcionCausa
		{
			get
			{
				return this._DescripcionCausa;
			}
			set
			{
				if ((this._DescripcionCausa != value))
				{
					this.OnDescripcionCausaChanging(value);
					this.SendPropertyChanging();
					this._DescripcionCausa = value;
					this.SendPropertyChanged("DescripcionCausa");
					this.OnDescripcionCausaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionEvento", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string DescripcionEvento
		{
			get
			{
				return this._DescripcionEvento;
			}
			set
			{
				if ((this._DescripcionEvento != value))
				{
					this.OnDescripcionEventoChanging(value);
					this.SendPropertyChanging();
					this._DescripcionEvento = value;
					this.SendPropertyChanged("DescripcionEvento");
					this.OnDescripcionEventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionConsecuencia", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string DescripcionConsecuencia
		{
			get
			{
				return this._DescripcionConsecuencia;
			}
			set
			{
				if ((this._DescripcionConsecuencia != value))
				{
					this.OnDescripcionConsecuenciaChanging(value);
					this.SendPropertyChanging();
					this._DescripcionConsecuencia = value;
					this.SendPropertyChanged("DescripcionConsecuencia");
					this.OnDescripcionConsecuenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaIdentificacion", DbType="Date NOT NULL")]
		public System.DateTime FechaIdentificacion
		{
			get
			{
				return this._FechaIdentificacion;
			}
			set
			{
				if ((this._FechaIdentificacion != value))
				{
					this.OnFechaIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaIdentificacion = value;
					this.SendPropertyChanged("FechaIdentificacion");
					this.OnFechaIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dependencia_Especifico", Storage="_Dependencia1", ThisKey="Dependencia", OtherKey="Nombre", IsForeignKey=true)]
		public Dependencia Dependencia1
		{
			get
			{
				return this._Dependencia1.Entity;
			}
			set
			{
				Dependencia previousValue = this._Dependencia1.Entity;
				if (((previousValue != value) 
							|| (this._Dependencia1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dependencia1.Entity = null;
						previousValue.Especifico.Remove(this);
					}
					this._Dependencia1.Entity = value;
					if ((value != null))
					{
						value.Especifico.Add(this);
						this._Dependencia = value.Nombre;
					}
					else
					{
						this._Dependencia = default(string);
					}
					this.SendPropertyChanged("Dependencia1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DireccionDirect_Especifico", Storage="_DireccionDirect", ThisKey="Direccion", OtherKey="Codigo", IsForeignKey=true)]
		public DireccionDirect DireccionDirect
		{
			get
			{
				return this._DireccionDirect.Entity;
			}
			set
			{
				DireccionDirect previousValue = this._DireccionDirect.Entity;
				if (((previousValue != value) 
							|| (this._DireccionDirect.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DireccionDirect.Entity = null;
						previousValue.Especifico.Remove(this);
					}
					this._DireccionDirect.Entity = value;
					if ((value != null))
					{
						value.Especifico.Add(this);
						this._Direccion = value.Codigo;
					}
					else
					{
						this._Direccion = default(string);
					}
					this.SendPropertyChanged("DireccionDirect");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EvaluacionControlesActualesRiesgo")]
	public partial class EvaluacionControlesActualesRiesgo
	{
		
		private System.Nullable<int> _CodigoEvaluacion;
		
		private string _DescripcionControlActual;
		
		private System.Nullable<int> _DisminucionProbabilidad;
		
		private System.Nullable<int> _DisminucionImpacto;
		
		private System.Nullable<int> _ProbabilidadControlActual;
		
		private System.Nullable<int> _ImpactoControlActual;
		
		private System.Nullable<int> _NivelRiesgoResidual;
		
		private int _Codigo;
		
		public EvaluacionControlesActualesRiesgo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoEvaluacion", DbType="Int")]
		public System.Nullable<int> CodigoEvaluacion
		{
			get
			{
				return this._CodigoEvaluacion;
			}
			set
			{
				if ((this._CodigoEvaluacion != value))
				{
					this._CodigoEvaluacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionControlActual", DbType="VarChar(100)")]
		public string DescripcionControlActual
		{
			get
			{
				return this._DescripcionControlActual;
			}
			set
			{
				if ((this._DescripcionControlActual != value))
				{
					this._DescripcionControlActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisminucionProbabilidad", DbType="Int")]
		public System.Nullable<int> DisminucionProbabilidad
		{
			get
			{
				return this._DisminucionProbabilidad;
			}
			set
			{
				if ((this._DisminucionProbabilidad != value))
				{
					this._DisminucionProbabilidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisminucionImpacto", DbType="Int")]
		public System.Nullable<int> DisminucionImpacto
		{
			get
			{
				return this._DisminucionImpacto;
			}
			set
			{
				if ((this._DisminucionImpacto != value))
				{
					this._DisminucionImpacto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProbabilidadControlActual", DbType="Int")]
		public System.Nullable<int> ProbabilidadControlActual
		{
			get
			{
				return this._ProbabilidadControlActual;
			}
			set
			{
				if ((this._ProbabilidadControlActual != value))
				{
					this._ProbabilidadControlActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImpactoControlActual", DbType="Int")]
		public System.Nullable<int> ImpactoControlActual
		{
			get
			{
				return this._ImpactoControlActual;
			}
			set
			{
				if ((this._ImpactoControlActual != value))
				{
					this._ImpactoControlActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelRiesgoResidual", DbType="Int")]
		public System.Nullable<int> NivelRiesgoResidual
		{
			get
			{
				return this._NivelRiesgoResidual;
			}
			set
			{
				if ((this._NivelRiesgoResidual != value))
				{
					this._NivelRiesgoResidual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EvalucionRiesgo")]
	public partial class EvalucionRiesgo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _TipoRiesgo;
		
		private System.Nullable<int> _CodigoRiesgo;
		
		private string _Evento;
		
		private System.Nullable<int> _Probabilidad;
		
		private System.Nullable<int> _Impacto;
		
		private System.Nullable<int> _NivelRiesgoInherente;
		
		private int _Codigo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTipoRiesgoChanging(System.Nullable<int> value);
    partial void OnTipoRiesgoChanged();
    partial void OnCodigoRiesgoChanging(System.Nullable<int> value);
    partial void OnCodigoRiesgoChanged();
    partial void OnEventoChanging(string value);
    partial void OnEventoChanged();
    partial void OnProbabilidadChanging(System.Nullable<int> value);
    partial void OnProbabilidadChanged();
    partial void OnImpactoChanging(System.Nullable<int> value);
    partial void OnImpactoChanged();
    partial void OnNivelRiesgoInherenteChanging(System.Nullable<int> value);
    partial void OnNivelRiesgoInherenteChanged();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    #endregion
		
		public EvalucionRiesgo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoRiesgo", DbType="Int")]
		public System.Nullable<int> TipoRiesgo
		{
			get
			{
				return this._TipoRiesgo;
			}
			set
			{
				if ((this._TipoRiesgo != value))
				{
					this.OnTipoRiesgoChanging(value);
					this.SendPropertyChanging();
					this._TipoRiesgo = value;
					this.SendPropertyChanged("TipoRiesgo");
					this.OnTipoRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoRiesgo", DbType="Int")]
		public System.Nullable<int> CodigoRiesgo
		{
			get
			{
				return this._CodigoRiesgo;
			}
			set
			{
				if ((this._CodigoRiesgo != value))
				{
					this.OnCodigoRiesgoChanging(value);
					this.SendPropertyChanging();
					this._CodigoRiesgo = value;
					this.SendPropertyChanged("CodigoRiesgo");
					this.OnCodigoRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Evento", DbType="VarChar(150)")]
		public string Evento
		{
			get
			{
				return this._Evento;
			}
			set
			{
				if ((this._Evento != value))
				{
					this.OnEventoChanging(value);
					this.SendPropertyChanging();
					this._Evento = value;
					this.SendPropertyChanged("Evento");
					this.OnEventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Probabilidad", DbType="Int")]
		public System.Nullable<int> Probabilidad
		{
			get
			{
				return this._Probabilidad;
			}
			set
			{
				if ((this._Probabilidad != value))
				{
					this.OnProbabilidadChanging(value);
					this.SendPropertyChanging();
					this._Probabilidad = value;
					this.SendPropertyChanged("Probabilidad");
					this.OnProbabilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impacto", DbType="Int")]
		public System.Nullable<int> Impacto
		{
			get
			{
				return this._Impacto;
			}
			set
			{
				if ((this._Impacto != value))
				{
					this.OnImpactoChanging(value);
					this.SendPropertyChanging();
					this._Impacto = value;
					this.SendPropertyChanged("Impacto");
					this.OnImpactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelRiesgoInherente", DbType="Int")]
		public System.Nullable<int> NivelRiesgoInherente
		{
			get
			{
				return this._NivelRiesgoInherente;
			}
			set
			{
				if ((this._NivelRiesgoInherente != value))
				{
					this.OnNivelRiesgoInherenteChanging(value);
					this.SendPropertyChanging();
					this._NivelRiesgoInherente = value;
					this.SendPropertyChanged("NivelRiesgoInherente");
					this.OnNivelRiesgoInherenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Generales")]
	public partial class Generales : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Objetivo;
		
		private string _CodigoRiesgo;
		
		private string _CodigoCausa;
		
		private string _Causa;
		
		private string _Definicion;
		
		private string _Categoria;
		
		private string _SubCategoria;
		
		private string _DescripcionCausa;
		
		private string _DescripcionEvento;
		
		private string _DescripcionConsecuencia;
		
		private System.DateTime _FechaIdenti;
		
		private EntityRef<Diccionario> _Diccionario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnObjetivoChanging(string value);
    partial void OnObjetivoChanged();
    partial void OnCodigoRiesgoChanging(string value);
    partial void OnCodigoRiesgoChanged();
    partial void OnCodigoCausaChanging(string value);
    partial void OnCodigoCausaChanged();
    partial void OnCausaChanging(string value);
    partial void OnCausaChanged();
    partial void OnDefinicionChanging(string value);
    partial void OnDefinicionChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnSubCategoriaChanging(string value);
    partial void OnSubCategoriaChanged();
    partial void OnDescripcionCausaChanging(string value);
    partial void OnDescripcionCausaChanged();
    partial void OnDescripcionEventoChanging(string value);
    partial void OnDescripcionEventoChanged();
    partial void OnDescripcionConsecuenciaChanging(string value);
    partial void OnDescripcionConsecuenciaChanged();
    partial void OnFechaIdentiChanging(System.DateTime value);
    partial void OnFechaIdentiChanged();
    #endregion
		
		public Generales()
		{
			this._Diccionario = default(EntityRef<Diccionario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Objetivo", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Objetivo
		{
			get
			{
				return this._Objetivo;
			}
			set
			{
				if ((this._Objetivo != value))
				{
					this.OnObjetivoChanging(value);
					this.SendPropertyChanging();
					this._Objetivo = value;
					this.SendPropertyChanged("Objetivo");
					this.OnObjetivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoRiesgo", DbType="VarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodigoRiesgo
		{
			get
			{
				return this._CodigoRiesgo;
			}
			set
			{
				if ((this._CodigoRiesgo != value))
				{
					this.OnCodigoRiesgoChanging(value);
					this.SendPropertyChanging();
					this._CodigoRiesgo = value;
					this.SendPropertyChanged("CodigoRiesgo");
					this.OnCodigoRiesgoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCausa", DbType="VarChar(50)")]
		public string CodigoCausa
		{
			get
			{
				return this._CodigoCausa;
			}
			set
			{
				if ((this._CodigoCausa != value))
				{
					if (this._Diccionario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoCausaChanging(value);
					this.SendPropertyChanging();
					this._CodigoCausa = value;
					this.SendPropertyChanged("CodigoCausa");
					this.OnCodigoCausaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Causa", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Causa
		{
			get
			{
				return this._Causa;
			}
			set
			{
				if ((this._Causa != value))
				{
					this.OnCausaChanging(value);
					this.SendPropertyChanging();
					this._Causa = value;
					this.SendPropertyChanged("Causa");
					this.OnCausaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Definicion", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Definicion
		{
			get
			{
				return this._Definicion;
			}
			set
			{
				if ((this._Definicion != value))
				{
					this.OnDefinicionChanging(value);
					this.SendPropertyChanging();
					this._Definicion = value;
					this.SendPropertyChanged("Definicion");
					this.OnDefinicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoria", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string SubCategoria
		{
			get
			{
				return this._SubCategoria;
			}
			set
			{
				if ((this._SubCategoria != value))
				{
					this.OnSubCategoriaChanging(value);
					this.SendPropertyChanging();
					this._SubCategoria = value;
					this.SendPropertyChanged("SubCategoria");
					this.OnSubCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionCausa", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string DescripcionCausa
		{
			get
			{
				return this._DescripcionCausa;
			}
			set
			{
				if ((this._DescripcionCausa != value))
				{
					this.OnDescripcionCausaChanging(value);
					this.SendPropertyChanging();
					this._DescripcionCausa = value;
					this.SendPropertyChanged("DescripcionCausa");
					this.OnDescripcionCausaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionEvento", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string DescripcionEvento
		{
			get
			{
				return this._DescripcionEvento;
			}
			set
			{
				if ((this._DescripcionEvento != value))
				{
					this.OnDescripcionEventoChanging(value);
					this.SendPropertyChanging();
					this._DescripcionEvento = value;
					this.SendPropertyChanged("DescripcionEvento");
					this.OnDescripcionEventoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionConsecuencia", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string DescripcionConsecuencia
		{
			get
			{
				return this._DescripcionConsecuencia;
			}
			set
			{
				if ((this._DescripcionConsecuencia != value))
				{
					this.OnDescripcionConsecuenciaChanging(value);
					this.SendPropertyChanging();
					this._DescripcionConsecuencia = value;
					this.SendPropertyChanged("DescripcionConsecuencia");
					this.OnDescripcionConsecuenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaIdenti", DbType="Date NOT NULL")]
		public System.DateTime FechaIdenti
		{
			get
			{
				return this._FechaIdenti;
			}
			set
			{
				if ((this._FechaIdenti != value))
				{
					this.OnFechaIdentiChanging(value);
					this.SendPropertyChanging();
					this._FechaIdenti = value;
					this.SendPropertyChanged("FechaIdenti");
					this.OnFechaIdentiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Diccionario_Generales", Storage="_Diccionario", ThisKey="CodigoCausa", OtherKey="Codigo", IsForeignKey=true)]
		public Diccionario Diccionario
		{
			get
			{
				return this._Diccionario.Entity;
			}
			set
			{
				Diccionario previousValue = this._Diccionario.Entity;
				if (((previousValue != value) 
							|| (this._Diccionario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Diccionario.Entity = null;
						previousValue.Generales.Remove(this);
					}
					this._Diccionario.Entity = value;
					if ((value != null))
					{
						value.Generales.Add(this);
						this._CodigoCausa = value.Codigo;
					}
					else
					{
						this._CodigoCausa = default(string);
					}
					this.SendPropertyChanged("Diccionario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MedidadControlRiesgoPropuesto")]
	public partial class MedidadControlRiesgoPropuesto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodgioControlPropuesto;
		
		private string _FechaAplicacion;
		
		private string _DescripcionControlPropuesto;
		
		private System.Nullable<int> _DisminucionProbabilidad;
		
		private System.Nullable<int> _DisminucionImpacto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodgioControlPropuestoChanging(int value);
    partial void OnCodgioControlPropuestoChanged();
    partial void OnFechaAplicacionChanging(string value);
    partial void OnFechaAplicacionChanged();
    partial void OnDescripcionControlPropuestoChanging(string value);
    partial void OnDescripcionControlPropuestoChanged();
    partial void OnDisminucionProbabilidadChanging(System.Nullable<int> value);
    partial void OnDisminucionProbabilidadChanged();
    partial void OnDisminucionImpactoChanging(System.Nullable<int> value);
    partial void OnDisminucionImpactoChanged();
    #endregion
		
		public MedidadControlRiesgoPropuesto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodgioControlPropuesto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CodgioControlPropuesto
		{
			get
			{
				return this._CodgioControlPropuesto;
			}
			set
			{
				if ((this._CodgioControlPropuesto != value))
				{
					this.OnCodgioControlPropuestoChanging(value);
					this.SendPropertyChanging();
					this._CodgioControlPropuesto = value;
					this.SendPropertyChanged("CodgioControlPropuesto");
					this.OnCodgioControlPropuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAplicacion", DbType="VarChar(100)")]
		public string FechaAplicacion
		{
			get
			{
				return this._FechaAplicacion;
			}
			set
			{
				if ((this._FechaAplicacion != value))
				{
					this.OnFechaAplicacionChanging(value);
					this.SendPropertyChanging();
					this._FechaAplicacion = value;
					this.SendPropertyChanged("FechaAplicacion");
					this.OnFechaAplicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionControlPropuesto", DbType="VarChar(100)")]
		public string DescripcionControlPropuesto
		{
			get
			{
				return this._DescripcionControlPropuesto;
			}
			set
			{
				if ((this._DescripcionControlPropuesto != value))
				{
					this.OnDescripcionControlPropuestoChanging(value);
					this.SendPropertyChanging();
					this._DescripcionControlPropuesto = value;
					this.SendPropertyChanged("DescripcionControlPropuesto");
					this.OnDescripcionControlPropuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisminucionProbabilidad", DbType="Int")]
		public System.Nullable<int> DisminucionProbabilidad
		{
			get
			{
				return this._DisminucionProbabilidad;
			}
			set
			{
				if ((this._DisminucionProbabilidad != value))
				{
					this.OnDisminucionProbabilidadChanging(value);
					this.SendPropertyChanging();
					this._DisminucionProbabilidad = value;
					this.SendPropertyChanged("DisminucionProbabilidad");
					this.OnDisminucionProbabilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisminucionImpacto", DbType="Int")]
		public System.Nullable<int> DisminucionImpacto
		{
			get
			{
				return this._DisminucionImpacto;
			}
			set
			{
				if ((this._DisminucionImpacto != value))
				{
					this.OnDisminucionImpactoChanging(value);
					this.SendPropertyChanging();
					this._DisminucionImpacto = value;
					this.SendPropertyChanged("DisminucionImpacto");
					this.OnDisminucionImpactoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RiesgoPropuesto")]
	public partial class RiesgoPropuesto
	{
		
		private string _Codigo;
		
		public RiesgoPropuesto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NChar(10)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Riesgos")]
	public partial class Riesgos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Numero;
		
		private int _Codigo;
		
		private string _EventoPresentado;
		
		private EntitySet<Administracion> _Administracion;
		
		private EntitySet<Administracion> _Administracion1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumeroChanging(int value);
    partial void OnNumeroChanged();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnEventoPresentadoChanging(string value);
    partial void OnEventoPresentadoChanged();
    #endregion
		
		public Riesgos()
		{
			this._Administracion = new EntitySet<Administracion>(new Action<Administracion>(this.attach_Administracion), new Action<Administracion>(this.detach_Administracion));
			this._Administracion1 = new EntitySet<Administracion>(new Action<Administracion>(this.attach_Administracion1), new Action<Administracion>(this.detach_Administracion1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventoPresentado", DbType="VarChar(150)")]
		public string EventoPresentado
		{
			get
			{
				return this._EventoPresentado;
			}
			set
			{
				if ((this._EventoPresentado != value))
				{
					this.OnEventoPresentadoChanging(value);
					this.SendPropertyChanging();
					this._EventoPresentado = value;
					this.SendPropertyChanged("EventoPresentado");
					this.OnEventoPresentadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Riesgos_Administracion", Storage="_Administracion", ThisKey="Codigo", OtherKey="Codigo")]
		public EntitySet<Administracion> Administracion
		{
			get
			{
				return this._Administracion;
			}
			set
			{
				this._Administracion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Riesgos_Administracion1", Storage="_Administracion1", ThisKey="Codigo", OtherKey="Codigo")]
		public EntitySet<Administracion> Administracion1
		{
			get
			{
				return this._Administracion1;
			}
			set
			{
				this._Administracion1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Administracion(Administracion entity)
		{
			this.SendPropertyChanging();
			entity.Riesgos = this;
		}
		
		private void detach_Administracion(Administracion entity)
		{
			this.SendPropertyChanging();
			entity.Riesgos = null;
		}
		
		private void attach_Administracion1(Administracion entity)
		{
			this.SendPropertyChanging();
			entity.Riesgos1 = this;
		}
		
		private void detach_Administracion1(Administracion entity)
		{
			this.SendPropertyChanging();
			entity.Riesgos1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario
	{
		
		private string _Usuario1;
		
		private string _Contra;
		
		public Usuario()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Usuario", Storage="_Usuario1", DbType="VarChar(100)")]
		public string Usuario1
		{
			get
			{
				return this._Usuario1;
			}
			set
			{
				if ((this._Usuario1 != value))
				{
					this._Usuario1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contra", DbType="VarChar(50)")]
		public string Contra
		{
			get
			{
				return this._Contra;
			}
			set
			{
				if ((this._Contra != value))
				{
					this._Contra = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
